Vactor0911/wanna-trip

- package-lock.json
- src/pages/Template.tsx
**개요**
costar 브랜치 복구 완료
**변경점**
1. costar 브랜치 복구 작업 끝
**추가 내용**
> costar 브랜치 복구 완료

- src/pages/Login.tsx
- src/pages/NewTemplate.tsx
- src/pages/Register.tsx
**개요**
카카오 간편 로그인 시 첫 로그인의 토큰 및 세션이 유지되는 버그가 발생하여
한 디바이스에서 다른 계정으로 로그인 하지 못하는 버그가 있었음.
이를 해결함
**변경점**
1. Login.tsx 에서 세션 및 토큰을 초기화 하는 기능 추가
2. 카카오 로그인 화면으로 이동 시 &prompt=login 속성 추가
**추가 내용**
&prompt=login 란 접속할 때마다 다시 로그인하는 속성임
> 카카오 간편 로그인 버그 해결

- src/components/LoginButton.tsx
- src/pages/NewTemplate.tsx
**개요**
템플릿 페이지에서 로그인 상태의 컴포넌트를 추가함
**변경점**
1. 템플릿 페이지에서 로그인 상태의 컴포넌트를 추가
**추가 내용**
> 템플릿 페이지에 로그인 상태의 컴포넌트 추가

- src/pages/Login.tsx
**개요**
로그인 화면 이메일 저장 체크박스 위치 재정렬
**변경점**
1. 로그인 화면 이메일 저장 체크박스 위치 재정렬
**추가 내용**
> 이메일 저장 체크박스 위치 재정렬

- src/App.tsx
- src/components/Card.tsx
- src/components/Content.tsx
- src/pages/NewTemplate.tsx
- src/pages/Template.tsx
**개요**
카드 추가, 복사, 삭제 기능 구현
**변경점**
1. 카드 추가 기능 구현
2. 카드 복사 기능 구현
3. 카드 삭제 기능 구현
**추가 내용**
> Card.tsx에 카드 추가, 복사, 삭제 기능 추가

- src/components/Card.tsx
**개요**
카드 계획 추가하기 버튼 및 계획 내용 변경 기능 구현
**변경점**
카드 계획 추가하기 버튼 및 계획 내용 변경 기능 구현
1. 카드 계획 추가하기 버튼 기능 구현
2. 카드 계획 내용 변경 기능 구현
**추가 내용**
석헌 오빠 깃허브 코드랑 섞음
> 카드 계획추가하기 버튼 및 계획 내용 변경 기능 구현

- src/pages/Login.tsx
- src/pages/NewTemplate.tsx
- src/pages/Register.tsx
- src/pages/Template.tsx
- src/state/index.ts
**개요**
백엔드 통신 서버 주소 일괄 변경
**변경점**
1. 백엔드 통신 서버 주소 일괄 변경
**추가 내용**
> 백엔드 통신 서버 주소 일괄 변경

- src/components/Card.tsx
**개요**
card 안에 text 사용자가 직접 쓸 수 있도록 구현
**변경점**
1. card 안에 text 수정 기능 구현
**추가 내용**
> card 안에 text 사용자가 직접 쓸 수 있도록 구현함

- src/App.tsx
- src/pages/Login.tsx
- src/state/index.ts
**개요**
로그인 페이지 이메일 저장 기능 버그 수정
**변경점**
1. 이메일 저장 기능 버그 수정
**추가 내용**
> 이메일 저장 기능 버그 수정

- src/pages/Login.tsx
- src/pages/NewTemplate.tsx
- src/pages/Template.tsx
- src/state/index.ts
**개요**
로컬 스토리지 Key 값 재수정
**변경점**
1. 로컬 스토리지 Key 값 재수정
**추가 내용**
> 로컬 스토리지 Key 값 재수정

- src/components/BoardOne.tsx
**개요**
board1 costar 연습용 추가
**변경점**
board1 costar 연습용 추가
1. board.tsx 페이지 대신 연습용 페이지 추가
2. boardone.tsx  costar 연습용 페이지 추가
**추가 내용**
> board1 costar 연습용

- .github/workflows/deploy.yml
**개요**
deploy.yml 워크플로우 생성
**변경점**
1. deploy.yml 워크플로우 생성
**추가 내용**
더 설명할 내용이 있다면 적어주세요.
> deploy.yml 워크플로우 생성

- .github/workflows/deploy.yml
**개요**
deploy.yml 워크플로우 수정
**변경점**
1. deploy.yml 워크플로우 수정
**추가 내용**
> deploy.yml 워크플로우 수정

- .github/workflows/deploy.yml
**개요**
deploy.yml 파일 수정
**변경점**
1. deploy.yml 파일 수정
**추가 내용**
> deploy.yml 파일 수정

- package-lock.json
- src/App.tsx
- src/pages/Main.tsx
- src/utils/index.ts
- vite.config.ts
**개요**
Main 페이지 리팩토링
**변경점**
1. ThemeProvider 요소 추가
2. Mui 테마 생성
3. ngrok allowed hosts 속성 추가
4. 라이브러리 버전 업데이트
5. Main 페이지 리팩토링
**추가 내용**
> Main 페이지 리팩토링

- src/pages/Login.tsx
**개요**
카카오 간편 로그인 시 다시 로그인페이지로 리다이렉트 되는 오류를 해결
**변경점**
1. 카카오 간편 로그인 오류 수정
**추가 내용**
> 카카오 간편 로그인 수정

- src/App.tsx
- src/components/TokenRefresher.tsx
- src/pages/Login.tsx
- src/pages/Register.tsx
- src/pages/Template.tsx
- src/state/index.ts
- src/utils/axiosInstance.ts
- vite.config.ts
**개요**
프로젝트 최적화 및 오류 수정
**변경점**
1. TokenRefresher 위치 조정
2. API 요청 인터셉터 버그 수정 및 최적화
3. Ngrok 설정 수정
4. 라우터 수정
**추가 내용**
> 프로젝트 최적화 및 오류 수정

- src/components/Board.tsx
- src/components/Header.tsx
- src/components/OutlinedTextField.tsx
- src/components/SectionHeader.tsx
- src/pages/Login.tsx
- src/pages/Main.tsx
- src/pages/Register.tsx
- src/pages/Template.tsx
- src/utils/theme.ts
**개요**
페이지 및 컴포넌트 스타일 수정
**변경점**
1. theme 경로 재설정
2. 검정색 테마 추가
3. 시작하기 버튼 링크 추가
4. 페이지 및 컴포넌트 스타일 수정
**추가 내용**
> 페이지 및 컴포넌트 스타일 수정

- src/pages/Login.tsx
- src/pages/Register.tsx
**개요**
아이콘 조건 수정
**변경점**
1. 눈 아이콘 조건 수정
> 눈 아이콘 조건 수정

- src/utils/axiosInstance.ts
**개요**
인터셉터에 http 오류 코드 수정
**변경점**
1. 인터셉터에 429 오류 처리 조건 추가
> 인터셉터에 429 오류 처리 조건 추가

- src/components/Card.tsx
- src/components/CardEditDialog.tsx
- src/components/Header.tsx
- src/components/NaverMap.tsx
- src/components/SquareTemplateCard.tsx
- src/components/text_editor/CardTextEditor.tsx
- src/utils/theme.ts
**개요**
카드 잠금 적용시 에디터 상호작용 비활성화 기능 추가
**변경점**
1. 카드 잠금 적용시 에디터 상호작용 비활성화 기능 추가
2. 카드 요소 테두리 변경
3. 카드 잠금 표시 추가
**추가 내용**
> 카드 잠금 적용시 에디터 상호작용 비활성화 기능 추가

- package-lock.json
**개요**
라이브러리 업데이트
**변경점**
1. 라이브러리 업데이트
**추가 내용**
> 라이브러리 업데이트

- package-lock.json
- package.json
- src/components/PdfDownloadButton.tsx
- src/pages/Template.tsx
- src/utils/excelExport.ts
- src/utils/pdfExport.ts
**개요**
HTML 엔티티 자동 디코딩으로 변경 및 출력 형식 변경, PDF 기능 구현
**변경점**
어떤 작업들이 이루어졌는지 모두 기술해주세요.
1. HTML 엔티티 자동 디코딩 변경
2. 출력 형식 변경
3. PDF 기능 구현 (임시)
**추가 내용**
더 설명할 내용이 있다면 적어주세요.
> HTML 엔티티 자동 디코딩으로 변경 및 출력 형식 변경, PDF 기능 구현
